import { ValuePiece } from "./ValuePiece";
import { Joker } from "./Joker";
import { TableFactory } from "./TableFactory";

const elements = new Set([
    new ValuePiece("red",1),
    new ValuePiece("red",5),
    new ValuePiece("red",5),
    new ValuePiece("red",6),
    new ValuePiece("red",7),
    new ValuePiece("red",8),
    new ValuePiece("red",10),
    new ValuePiece("red",11),
    new ValuePiece("red",13),
    new ValuePiece("green",1),
    new ValuePiece("green",2),
    new ValuePiece("green",2),
    new ValuePiece("green",3),
    new ValuePiece("green",4),
    new ValuePiece("green",5),
    new ValuePiece("green",6),
    new ValuePiece("green",7),
    new ValuePiece("green",8),
    new ValuePiece("green",9),
    new ValuePiece("green",11),
    new ValuePiece("green",12),
    new ValuePiece("green",13),
    new ValuePiece("green",13),
    new ValuePiece("blue",1),
    new ValuePiece("blue",2),
    new ValuePiece("blue",3),
    new ValuePiece("blue",4),
    new ValuePiece("blue",5),
    new ValuePiece("blue",6),
    new ValuePiece("blue",7),
    new ValuePiece("blue",8),
    new ValuePiece("blue",10),
    new ValuePiece("blue",10),
    new ValuePiece("blue",11),
    new ValuePiece("blue",11),
    new ValuePiece("blue",12),
    new ValuePiece("blue",13),
    new ValuePiece("blue",13),
    new ValuePiece("orange",1),
    new ValuePiece("orange",2),
    new ValuePiece("orange",2),
    new ValuePiece("orange",3),
    new ValuePiece("orange",4),
    new ValuePiece("orange",5),
    new ValuePiece("orange",5),
    new ValuePiece("orange",6),
    new ValuePiece("orange",6),
    new ValuePiece("orange",7),
    new ValuePiece("orange",8),
    new ValuePiece("orange",9),
    new ValuePiece("orange",9),
    new ValuePiece("orange",10),
    new ValuePiece("orange",10),
    new ValuePiece("orange",11),
    new ValuePiece("orange",11),
    new ValuePiece("orange",12),
    new ValuePiece("orange",12),
    new ValuePiece("orange",13),
    new ValuePiece("orange",13),
    new Joker()]);

console.log("Computing possible tables with all of "+[ ... elements].sort()+"\n")

const tables = TableFactory.create(elements);

console.log("Found "+tables.size+" possible solutions.\n")
console.log([... tables].map(t => "TABLE: \n"+t.toString()).sort().join("\n\n------------------------\n\n"));
